// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHsm8qccenRGOMcM8RhfO1io_avy-TbnM',
    appId: '1:60657429493:web:7de5ef0a453a23b7270ebc',
    messagingSenderId: '60657429493',
    projectId: 'emailsign-75f98',
    authDomain: 'emailsign-75f98.firebaseapp.com',
    storageBucket: 'emailsign-75f98.appspot.com',
    measurementId: 'G-E3T8W51S4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrtRWD-Wr8aEGZExftZUGMddirrQRql08',
    appId: '1:60657429493:android:e2b9468744c2e772270ebc',
    messagingSenderId: '60657429493',
    projectId: 'emailsign-75f98',
    storageBucket: 'emailsign-75f98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2-TA6LxM2dfqEfvQjFPn1Rj3oKlhku4',
    appId: '1:60657429493:ios:2b45238293088978270ebc',
    messagingSenderId: '60657429493',
    projectId: 'emailsign-75f98',
    storageBucket: 'emailsign-75f98.appspot.com',
    iosClientId: '60657429493-0upigdt993l0f95nt73fu9en957bnrhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.working',
  );
}
